### PR TITLE
Update nodegit dependency

### LINKED ISSUE #15: Fix nodegit dependency
This is a new issue which combines these issues:

* https://github.com/kimmobrunfeldt/git-hours/issues/14
* https://github.com/kimmobrunfeldt/git-hours/issues/11

Workaround for the nodegit issues is to use node version 0.12x. You can do it either by using [nvm](https://github.com/creationix/nvm) or following the vagrant installation guide in readme.

The real solution is to update nodegit dependency or open up a new issue to nodegit repo if it isn't working with a new node release. I have now tested to update nodegit to version 0.8.0. It seems to work with node 5.0.0 but there's a new bug which makes it useless: https://github.com/nodegit/nodegit/issues/866. Let's wait until nodegit gets their releases together.

### PR DESCRIPTION
**Pull request by mrPjer**
The nodegit dependency previously used did not work with the latest
nodejs. Updating to the latest available nodegit fixes relevant errors.

Fixes "Error: Cannot find module '../build/Debug/nodegit.node'"
Closes #15 

I've tested git-hours on node v5.5.0 and everything seems to work ok.

### CODE REVIEW

**Comment by mrPjer** [comment]
Just noticed versioning shouldn't be touched. I'll reopen with just the dependency change.
