### PR TITLE
Update nodegit dependency and fix Travis build

### LINKED ISSUE #15: Fix nodegit dependency
This is a new issue which combines these issues:

* https://github.com/kimmobrunfeldt/git-hours/issues/14
* https://github.com/kimmobrunfeldt/git-hours/issues/11

Workaround for the nodegit issues is to use node version 0.12x. You can do it either by using [nvm](https://github.com/creationix/nvm) or following the vagrant installation guide in readme.

The real solution is to update nodegit dependency or open up a new issue to nodegit repo if it isn't working with a new node release. I have now tested to update nodegit to version 0.8.0. It seems to work with node 5.0.0 but there's a new bug which makes it useless: https://github.com/nodegit/nodegit/issues/866. Let's wait until nodegit gets their releases together.

### LINKED ISSUE #18: Doesn't work in detached HEAD state
It seems that this utility does not work when the repository is in detached HEAD state.

Running:

```
git checkout @~0
git hours
```

Results in:

```
Error: Reference 'refs/remotes/(HEAD/HEAD' not found
    at Error (native)
```

This is the reason why Travis CI builds fail with `Uncaught SyntaxError: Unexpected end of input`, which you reported in travis-ci/travis-ci#2493 and this can be confirmed by printing out stderror in any of the tests (the above error is displayed).

### PR DESCRIPTION
**Pull request by mrPjer**
The nodegit dependency previously used did not work with the latest nodejs. Updating to the latest available nodegit fixes relevant errors.

Fixes "Error: Cannot find module '../build/Debug/nodegit.node'"
Closes #15 
Closes #18 
Fixes errors when the repository is in detached HEAD state
Prints a proper error message if the current repository is a shallow copy.

I've tested git-hours on node v5.5.0 and everything seems to work ok.

### CODE REVIEW

**Comment by mrPjer** [comment]
So, this was supposed to be a quick fix to support newer node versions since git-hours stopped working on my machine, and turned into a fun debugging session once Travis decided that my builds weren't passing.

This PR should fix the Travis build (check the commits for details) and the program now also checks if the current repository is a shallow clone (which cannot be processed). There are also no errors if the repository is currently in detached HEAD state (such as what happens when Travis clones a repository).

**Comment by kimmobrunfeldt** [comment]
Amazing work! Thanks :) i'll try to release this asap.

**Comment by kimmobrunfeldt** [comment]
All this work is now released in https://github.com/kimmobrunfeldt/git-hours/releases/tag/1.2.0

**Comment by mrPjer** [comment]
Thanks!
